import { Asset, Workflow } from "./types"

export const assets: Asset[] = [
  {
    id: "agent-1",
    name: "Claims Processing Agent",
    description: "AI-powered claims processing agent that automates claim submission, validation, and adjudication with payer-specific rules engine.",
    summary: "Automates end-to-end claims processing with payer rule compliance",
    type: "agent",
    category: "AI Agents",
    publisher: "Azure Healthcare AI",
    publisherVerified: true,
    version: "3.2.0",
    downloads: 24850,
    rating: 4.9,
    tags: ["claims", "rcm", "healthcare", "billing"],
    pricing: "Enterprise",
    icon: "FileText",
    lastUpdated: "2026-02-15",
    publishedDate: "2025-04-12",
    orchestrationUsage: 1847,
    capabilities: ["Claim Validation", "Payer Rules", "Auto-Submission", "Error Detection"]
  },
  {
    id: "agent-2",
    name: "Denial Management Agent",
    description: "Intelligent denial prediction and management agent that identifies denial patterns, auto-generates appeals, and tracks resolution workflows.",
    summary: "Predicts denials, generates appeals, and maximizes claim recovery",
    type: "agent",
    category: "AI Agents",
    publisher: "RCM Solutions",
    publisherVerified: true,
    version: "2.8.1",
    downloads: 18930,
    rating: 4.8,
    tags: ["denials", "appeals", "rcm", "recovery"],
    pricing: "Enterprise",
    icon: "Shield",
    lastUpdated: "2026-02-20",
    publishedDate: "2025-05-03",
    orchestrationUsage: 1562,
    capabilities: ["Denial Prediction", "Appeal Generation", "Root Cause Analysis", "Recovery Tracking"]
  },
  {
    id: "mcp-1",
    name: "Epic EHR MCP Server",
    description: "Model Context Protocol server for Epic EHR integration. Access patient records, scheduling, orders, and clinical documentation via FHIR APIs.",
    summary: "Connects AI agents to Epic EHR for clinical data access",
    type: "mcp-server",
    category: "MCP Servers",
    publisher: "Azure Healthcare AI",
    publisherVerified: true,
    version: "2.4.0",
    downloads: 32100,
    rating: 4.9,
    tags: ["epic", "ehr", "fhir", "healthcare"],
    pricing: "Enterprise",
    icon: "Database",
    lastUpdated: "2026-02-18",
    publishedDate: "2025-02-20",
    orchestrationUsage: 2843,
    capabilities: ["Patient Records", "Order Management", "Scheduling", "FHIR R4 Support"]
  },
  {
    id: "mcp-2",
    name: "Clearinghouse MCP Server",
    description: "Connect AI agents to major clearinghouses (Availity, Change Healthcare, Trizetto). Submit claims, check eligibility, and track remittances.",
    summary: "Multi-clearinghouse integration for claims and eligibility",
    type: "mcp-server",
    category: "MCP Servers",
    publisher: "RCM Solutions",
    publisherVerified: true,
    version: "3.1.0",
    downloads: 28500,
    rating: 4.8,
    tags: ["clearinghouse", "claims", "eligibility", "rcm"],
    pricing: "Enterprise",
    icon: "GitBranch",
    lastUpdated: "2026-02-22",
    publishedDate: "2025-03-15",
    orchestrationUsage: 2456,
    capabilities: ["Claim Submission", "Eligibility Check", "ERA Processing", "Status Tracking"]
  },
  {
    id: "tool-1",
    name: "Medical Coding Assistant",
    description: "AI-powered ICD-10, CPT, and HCPCS code suggestion tool with NLP-based clinical documentation analysis and coding compliance checks.",
    summary: "Suggests accurate medical codes from clinical documentation",
    type: "mcp-tool",
    category: "MCP Tools",
    publisher: "CodeRight AI",
    publisherVerified: true,
    version: "4.1.0",
    downloads: 22300,
    rating: 4.7,
    tags: ["coding", "icd-10", "cpt", "compliance"],
    pricing: "Enterprise",
    icon: "Table",
    lastUpdated: "2026-02-10",
    publishedDate: "2025-06-22",
    orchestrationUsage: 1823,
    capabilities: ["ICD-10 Coding", "CPT Suggestion", "HCC Capture", "Compliance Audit"]
  },
  {
    id: "tool-2",
    name: "EOB/ERA Parser",
    description: "Extract and normalize remittance data from EOB documents and ERA files (835) with automatic posting recommendations.",
    summary: "Parses remittance advices and automates payment posting",
    type: "mcp-tool",
    category: "MCP Tools",
    publisher: "RCM Solutions",
    publisherVerified: true,
    version: "3.2.0",
    downloads: 19700,
    rating: 4.8,
    tags: ["era", "eob", "remittance", "posting"],
    pricing: "Enterprise",
    icon: "FileText",
    lastUpdated: "2026-02-12",
    publishedDate: "2025-05-10",
    orchestrationUsage: 1291,
    capabilities: ["835 Parsing", "EOB OCR", "Auto-Posting", "Variance Detection"]
  },
  {
    id: "model-gpt4o",
    name: "GPT-4o",
    description: "OpenAI's most capable multimodal model with vision, audio, and text understanding. Ideal for complex healthcare reasoning, document analysis, and multi-turn clinical conversations.",
    summary: "Flagship multimodal model for complex reasoning and vision tasks",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "2024-11-20",
    downloads: 245000,
    rating: 4.9,
    tags: ["multimodal", "vision", "reasoning", "healthcare"],
    pricing: "Enterprise",
    icon: "Brain",
    lastUpdated: "2026-02-15",
    publishedDate: "2025-01-10",
    orchestrationUsage: 8921,
    capabilities: ["Multimodal Input", "Clinical Reasoning", "Document Analysis", "Structured Output"]
  },
  {
    id: "model-gpt5chat",
    name: "GPT-5 Chat",
    description: "OpenAI's GPT-5 optimized for conversational healthcare workflows—patient intake, clinical Q&A, and care navigation with superior instruction-following.",
    summary: "Next-generation conversational model for healthcare assistants",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "2025-06",
    downloads: 189000,
    rating: 4.9,
    tags: ["chat", "conversational", "healthcare", "nlp"],
    pricing: "Enterprise",
    icon: "MessageSquare",
    lastUpdated: "2026-02-20",
    publishedDate: "2025-06-01",
    orchestrationUsage: 7234,
    capabilities: ["Patient Chat", "Clinical Q&A", "Care Navigation", "Multi-turn Dialogue"]
  },
  {
    id: "model-gpt52",
    name: "GPT-5.2",
    description: "Latest GPT-5.2 release with enhanced accuracy on medical benchmarks, improved HIPAA-safe output handling, and reduced hallucination rates for clinical applications.",
    summary: "Enhanced GPT-5 with improved clinical accuracy and safety",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "5.2",
    downloads: 134000,
    rating: 4.9,
    tags: ["gpt-5", "clinical", "safety", "healthcare"],
    pricing: "Enterprise",
    icon: "Brain",
    lastUpdated: "2026-02-28",
    publishedDate: "2025-11-01",
    orchestrationUsage: 5678,
    capabilities: ["Clinical Accuracy", "Hallucination Reduction", "Safe Outputs", "Medical Benchmarks"]
  },
  {
    id: "model-gpt5mini",
    name: "GPT-5 Mini",
    description: "Lightweight GPT-5 variant tuned for high-throughput healthcare workloads. Ideal for eligibility checks, code extraction, and claim scrubbing at scale.",
    summary: "Fast, cost-efficient GPT-5 for high-volume RCM tasks",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "5-mini",
    downloads: 98000,
    rating: 4.7,
    tags: ["efficiency", "rcm", "batch", "coding"],
    pricing: "Pro",
    icon: "Code",
    lastUpdated: "2026-02-10",
    publishedDate: "2025-07-15",
    orchestrationUsage: 4312,
    capabilities: ["Batch Processing", "Code Extraction", "Claim Scrubbing", "Low Latency"]
  },
  {
    id: "model-gpt5codex",
    name: "GPT-5 Codex",
    description: "Code-focused GPT-5 model for generating HL7/FHIR integration code, RCM automation scripts, and healthcare workflow definitions.",
    summary: "Code generation model for healthcare integrations and automation",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "5-codex",
    downloads: 67000,
    rating: 4.8,
    tags: ["code-gen", "fhir", "hl7", "automation"],
    pricing: "Enterprise",
    icon: "Code",
    lastUpdated: "2026-02-18",
    publishedDate: "2025-09-01",
    orchestrationUsage: 2890,
    capabilities: ["FHIR Code Gen", "HL7 Parsing", "API Scaffolding", "Workflow Scripts"]
  },
  {
    id: "model-o1",
    name: "o1",
    description: "OpenAI o1 reasoning model optimized for complex multi-step medical logic: differential diagnosis chains, coverage policy interpretation, and audit trail reasoning.",
    summary: "Chain-of-thought reasoning model for complex medical decisions",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "2024-12",
    downloads: 112000,
    rating: 4.9,
    tags: ["reasoning", "chain-of-thought", "diagnosis", "policy"],
    pricing: "Enterprise",
    icon: "Brain",
    lastUpdated: "2026-01-30",
    publishedDate: "2025-03-01",
    orchestrationUsage: 3456,
    capabilities: ["Multi-step Reasoning", "Policy Interpretation", "Differential Diagnosis", "Audit Trails"]
  },
  {
    id: "model-deepseek-r1",
    name: "DeepSeek R1",
    description: "Open-source reasoning model with strong performance on clinical benchmarks. Transparent chain-of-thought ideal for explainable AI requirements in healthcare.",
    summary: "Open-source reasoning model with explainable clinical outputs",
    type: "model",
    category: "Models",
    publisher: "DeepSeek / Microsoft",
    publisherVerified: true,
    version: "0528",
    downloads: 88000,
    rating: 4.7,
    tags: ["open-source", "reasoning", "explainable", "clinical"],
    pricing: "Enterprise",
    icon: "Brain",
    lastUpdated: "2026-02-01",
    publishedDate: "2025-05-28",
    orchestrationUsage: 2345,
    capabilities: ["Explainable AI", "Clinical Benchmarks", "Open Weights", "Chain-of-Thought"]
  },
  {
    id: "model-gpt-oss-120b",
    name: "GPT OSS 120B",
    description: "Microsoft's open-source 120B parameter model for on-premise and air-gapped healthcare deployments. Full HIPAA-compliance with no data egress.",
    summary: "120B open-source model for air-gapped healthcare deployments",
    type: "model",
    category: "Models",
    publisher: "Microsoft",
    publisherVerified: true,
    version: "120B",
    downloads: 45000,
    rating: 4.7,
    tags: ["open-source", "on-premise", "hipaa", "120b"],
    pricing: "Enterprise",
    icon: "Shield",
    lastUpdated: "2026-02-12",
    publishedDate: "2025-10-15",
    orchestrationUsage: 1876,
    capabilities: ["Air-Gapped Deploy", "HIPAA Compliant", "On-Premise", "No Data Egress"]
  },
  {
    id: "model-gpt4",
    name: "GPT-4",
    description: "OpenAI GPT-4 — the proven foundation for healthcare NLP, clinical summarization, and complex instruction following across EHR and RCM use cases.",
    summary: "Proven GPT-4 for healthcare NLP and clinical summarization",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "0613",
    downloads: 310000,
    rating: 4.8,
    tags: ["nlp", "summarization", "clinical", "ehr"],
    pricing: "Enterprise",
    icon: "Brain",
    lastUpdated: "2026-01-20",
    publishedDate: "2024-06-13",
    orchestrationUsage: 9845,
    capabilities: ["Clinical Summarization", "EHR Q&A", "Instruction Following", "Multi-language"]
  },
  {
    id: "model-gpt41",
    name: "GPT-4.1",
    description: "GPT-4.1 with improved long-context handling for large clinical documents, extended patient histories, and multi-document summarization.",
    summary: "Long-context GPT-4 for extended clinical records",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "4.1",
    downloads: 156000,
    rating: 4.8,
    tags: ["long-context", "clinical", "summarization", "ehr"],
    pricing: "Enterprise",
    icon: "Brain",
    lastUpdated: "2026-02-08",
    publishedDate: "2025-04-01",
    orchestrationUsage: 6123,
    capabilities: ["Long Context (256k)", "Multi-doc Summary", "History Analysis", "Clinical Notes"]
  },
  {
    id: "model-gpt35turbo",
    name: "GPT-3.5 Turbo",
    description: "Cost-optimized model for high-volume, lower-complexity healthcare tasks: eligibility lookups, claim status queries, and basic triage routing.",
    summary: "Fast, affordable model for high-volume routine healthcare tasks",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "0125",
    downloads: 520000,
    rating: 4.5,
    tags: ["cost-efficient", "batch", "eligibility", "routing"],
    pricing: "Starter",
    icon: "Code",
    lastUpdated: "2026-01-15",
    publishedDate: "2024-01-25",
    orchestrationUsage: 12340,
    capabilities: ["High Throughput", "Eligibility Queries", "Status Lookups", "Triage Routing"]
  },
  {
    id: "model-mistral-docai",
    name: "Mistral Document AI",
    description: "Mistral's document intelligence model specialized for healthcare forms — claim 1500, UB-04, EOBs, remittance advices, and insurance verification documents.",
    summary: "Document AI for healthcare claim forms and remittance advices",
    type: "model",
    category: "Models",
    publisher: "Mistral AI / Microsoft",
    publisherVerified: true,
    version: "2505",
    downloads: 78000,
    rating: 4.8,
    tags: ["document-ai", "ocr", "forms", "remittance"],
    pricing: "Enterprise",
    icon: "Eye",
    lastUpdated: "2026-02-22",
    publishedDate: "2025-05-01",
    orchestrationUsage: 3210,
    capabilities: ["Form 1500 / UB-04", "EOB Extraction", "Remittance Parsing", "High Accuracy OCR"]
  },
  {
    id: "model-gptimage15",
    name: "GPT Image 1.5",
    description: "Multimodal image generation and analysis model for medical imaging context — annotating radiology reports, generating patient-facing diagrams, and analyzing wound images.",
    summary: "Medical image analysis and generation for clinical context",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "1.5",
    downloads: 42000,
    rating: 4.7,
    tags: ["image", "vision", "radiology", "medical-imaging"],
    pricing: "Enterprise",
    icon: "Eye",
    lastUpdated: "2026-02-25",
    publishedDate: "2025-12-01",
    orchestrationUsage: 1567,
    capabilities: ["Medical Image Analysis", "Report Annotation", "Wound Assessment", "Patient Diagrams"]
  },
  {
    id: "model-gpt4omini-rt",
    name: "GPT-4o Mini Realtime",
    description: "Real-time speech model for voice-enabled healthcare workflows — ambient clinical documentation, patient phone bots, and dictation-to-note pipelines.",
    summary: "Real-time voice model for ambient clinical documentation",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "preview",
    downloads: 34000,
    rating: 4.7,
    tags: ["realtime", "voice", "ambient", "clinical-docs"],
    pricing: "Enterprise",
    icon: "MessageSquare",
    lastUpdated: "2026-02-18",
    publishedDate: "2025-10-01",
    orchestrationUsage: 1234,
    capabilities: ["Real-time Transcription", "Ambient Docs", "Phone Bots", "Voice-to-Note"]
  },
  {
    id: "model-gpt4omini-tts",
    name: "GPT-4o Mini TTS",
    description: "Text-to-speech model for healthcare patient communication — appointment reminders, medication instructions, and care plan narration in natural voice.",
    summary: "Natural text-to-speech for patient communication workflows",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "mini-tts",
    downloads: 28000,
    rating: 4.6,
    tags: ["tts", "voice", "patient-communication", "accessibility"],
    pricing: "Pro",
    icon: "MessageSquare",
    lastUpdated: "2026-02-14",
    publishedDate: "2025-11-01",
    orchestrationUsage: 987,
    capabilities: ["Natural Voice", "Appointment Reminders", "Medication Instructions", "Multi-language"]
  },
  {
    id: "model-ada002",
    name: "text-embedding-ada-002",
    description: "OpenAI's ada-002 embedding model for semantic search across clinical notes, ICD/CPT code retrieval, and similarity matching in healthcare knowledge bases.",
    summary: "Proven embedding model for clinical semantic search",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "2",
    downloads: 420000,
    rating: 4.6,
    tags: ["embeddings", "search", "rag", "clinical"],
    pricing: "Starter",
    icon: "Database",
    lastUpdated: "2026-01-10",
    publishedDate: "2024-01-01",
    orchestrationUsage: 15432,
    capabilities: ["Semantic Search", "RAG Pipelines", "Code Retrieval", "Similarity Matching"]
  },
  {
    id: "model-embed3small",
    name: "text-embedding-3-small",
    description: "Cost-efficient third-generation embedding model. Higher accuracy than ada-002 at lower cost — ideal for real-time eligibility lookups and claim similarity scoring.",
    summary: "Next-gen embedding model: better accuracy, lower cost",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "3-small",
    downloads: 234000,
    rating: 4.7,
    tags: ["embeddings", "search", "cost-efficient", "rag"],
    pricing: "Starter",
    icon: "Database",
    lastUpdated: "2026-01-25",
    publishedDate: "2025-01-25",
    orchestrationUsage: 11234,
    capabilities: ["High Accuracy Embeddings", "RAG", "Claim Similarity", "256 Dimensions"]
  },
  {
    id: "model-embed3large",
    name: "text-embedding-3-large",
    description: "High-dimension embedding model for nuanced clinical concept matching, complex FHIR resource retrieval, and large-scale healthcare knowledge graphs.",
    summary: "High-precision embeddings for complex clinical knowledge retrieval",
    type: "model",
    category: "Models",
    publisher: "Azure OpenAI",
    publisherVerified: true,
    version: "3-large",
    downloads: 98000,
    rating: 4.8,
    tags: ["embeddings", "knowledge-graph", "fhir", "clinical"],
    pricing: "Enterprise",
    icon: "Database",
    lastUpdated: "2026-01-28",
    publishedDate: "2025-01-25",
    orchestrationUsage: 5678,
    capabilities: ["3072 Dimensions", "FHIR Retrieval", "Knowledge Graphs", "Concept Matching"]
  },
  {
    id: "workflow-1",
    name: "End-to-End Claims Pipeline",
    description: "Complete claims lifecycle workflow from charge capture to payment posting with automated scrubbing, submission, and denial management.",
    summary: "Automates the entire claims lifecycle from charge to cash",
    type: "workflow-template",
    category: "Workflow Templates",
    publisher: "RCM Solutions",
    publisherVerified: true,
    version: "2.5.0",
    downloads: 8500,
    rating: 4.9,
    tags: ["claims", "rcm", "automation", "billing"],
    pricing: "Enterprise",
    icon: "Workflow",
    lastUpdated: "2026-02-08",
    publishedDate: "2025-04-18",
    orchestrationUsage: 934,
    capabilities: ["Charge Capture", "Claim Scrubbing", "Auto-Submission", "Payment Posting"]
  },
  {
    id: "workflow-2",
    name: "Prior Authorization Workflow",
    description: "Automated prior authorization request and tracking workflow with payer portal integration and status monitoring.",
    summary: "Streamlines prior auth requests and reduces approval delays",
    type: "workflow-template",
    category: "Workflow Templates",
    publisher: "Azure Healthcare AI",
    publisherVerified: true,
    version: "2.1.0",
    downloads: 6200,
    rating: 4.8,
    tags: ["prior-auth", "authorization", "payer", "compliance"],
    pricing: "Enterprise",
    icon: "Shield",
    lastUpdated: "2026-02-14",
    publishedDate: "2025-06-30",
    orchestrationUsage: 612,
    capabilities: ["Auto-Submission", "Status Tracking", "Doc Attachment", "Payer Integration"]
  },
  {
    id: "agent-3",
    name: "Patient Eligibility Agent",
    description: "Real-time patient eligibility verification agent with multi-payer support, coverage analysis, and benefit breakdown.",
    summary: "Verifies patient eligibility and benefits in real-time",
    type: "agent",
    category: "AI Agents",
    publisher: "Azure Healthcare AI",
    publisherVerified: true,
    version: "3.0.0",
    downloads: 21200,
    rating: 4.7,
    tags: ["eligibility", "verification", "payer", "benefits"],
    pricing: "Enterprise",
    icon: "BarChart",
    lastUpdated: "2026-02-19",
    publishedDate: "2025-08-05",
    orchestrationUsage: 1478,
    capabilities: ["Real-time Verify", "Multi-Payer", "Benefit Breakdown", "Coverage Analysis"]
  },
  {
    id: "agent-4",
    name: "Payment Posting Agent",
    description: "Automated payment posting agent that processes ERAs, reconciles payments, identifies underpayments, and manages adjustments.",
    summary: "Automates payment posting with variance detection",
    type: "agent",
    category: "AI Agents",
    publisher: "RCM Solutions",
    publisherVerified: true,
    version: "2.2.0",
    downloads: 15800,
    rating: 4.8,
    tags: ["posting", "payments", "era", "reconciliation"],
    pricing: "Enterprise",
    icon: "DollarSign",
    lastUpdated: "2026-02-21",
    publishedDate: "2025-07-14",
    orchestrationUsage: 1234,
    capabilities: ["ERA Processing", "Auto-Posting", "Underpayment ID", "Adjustment Mgmt"]
  },
  {
    id: "agent-5",
    name: "Patient Collections Agent",
    description: "Intelligent patient collections agent with personalized payment plans, automated outreach, and self-service payment portal integration.",
    summary: "Optimizes patient collections with AI-driven outreach",
    type: "agent",
    category: "AI Agents",
    publisher: "Azure Healthcare AI",
    publisherVerified: true,
    version: "1.8.0",
    downloads: 12400,
    rating: 4.6,
    tags: ["collections", "patient-pay", "outreach", "payments"],
    pricing: "Pro",
    icon: "MessageSquare",
    lastUpdated: "2026-02-18",
    publishedDate: "2025-09-20",
    orchestrationUsage: 892,
    capabilities: ["Payment Plans", "Auto Outreach", "Portal Integration", "Propensity Scoring"]
  },
  {
    id: "mcp-3",
    name: "Payer Portal MCP Server",
    description: "Unified payer portal integration for major commercial and government payers. Check claims status, submit appeals, and download EOBs.",
    summary: "Single integration for multi-payer portal automation",
    type: "mcp-server",
    category: "MCP Servers",
    publisher: "RCM Solutions",
    publisherVerified: true,
    version: "2.5.0",
    downloads: 18900,
    rating: 4.7,
    tags: ["payer", "portal", "claims", "automation"],
    pricing: "Enterprise",
    icon: "MessageCircle",
    lastUpdated: "2026-02-16",
    publishedDate: "2025-05-28",
    orchestrationUsage: 1734,
    capabilities: ["Status Check", "Appeal Submit", "EOB Download", "Auth Tracking"]
  },
  {
    id: "tool-3",
    name: "Charge Capture Tool",
    description: "AI-powered charge capture from clinical documentation with CPT/ICD mapping, modifier suggestions, and compliance validation.",
    summary: "Captures charges from clinical notes with high accuracy",
    type: "mcp-tool",
    category: "MCP Tools",
    publisher: "CodeRight AI",
    publisherVerified: true,
    version: "2.3.0",
    downloads: 14500,
    rating: 4.6,
    tags: ["charge-capture", "coding", "documentation", "compliance"],
    pricing: "Enterprise",
    icon: "Code",
    lastUpdated: "2026-02-14",
    publishedDate: "2025-08-12",
    orchestrationUsage: 978,
    capabilities: ["Auto Capture", "CPT Mapping", "Modifier Suggest", "Compliance Check"]
  },
  {
    id: "workflow-3",
    name: "Denial Prevention Pipeline",
    description: "Proactive denial prevention workflow that identifies at-risk claims before submission, applies corrections, and tracks prevention metrics.",
    summary: "Prevents denials before they happen with predictive AI",
    type: "workflow-template",
    category: "Workflow Templates",
    publisher: "RCM Solutions",
    publisherVerified: true,
    version: "1.8.0",
    downloads: 5400,
    rating: 4.7,
    tags: ["denials", "prevention", "predictive", "quality"],
    pricing: "Enterprise",
    icon: "Workflow",
    lastUpdated: "2026-02-10",
    publishedDate: "2025-10-05",
    orchestrationUsage: 456,
    capabilities: ["Risk Scoring", "Auto-Correction", "Prevention Metrics", "Trend Analysis"]
  }
]

export const sampleWorkflows: Workflow[] = [
  {
    id: "wf-1",
    name: "Claims Processing Pipeline",
    description: "End-to-end claims workflow with eligibility check, coding validation, and denial management",
    nodes: [
      {
        id: "trigger-1",
        type: "trigger",
        position: { x: 100, y: 200 },
        data: { label: "Charge Received", description: "New charge from EHR" }
      },
      {
        id: "agent-1",
        type: "agent",
        position: { x: 300, y: 200 },
        data: { label: "Eligibility Agent", description: "Verifies patient coverage" }
      },
      {
        id: "tool-1",
        type: "tool",
        position: { x: 500, y: 200 },
        data: { label: "Medical Coding", description: "Validates ICD/CPT codes" }
      },
      {
        id: "condition-1",
        type: "condition",
        position: { x: 700, y: 200 },
        data: { label: "Clean Claim?", description: "Passes scrubbing rules?" }
      },
      {
        id: "agent-2",
        type: "agent",
        position: { x: 900, y: 100 },
        data: { label: "Claims Agent", description: "Submits to clearinghouse" }
      },
      {
        id: "agent-3",
        type: "agent",
        position: { x: 900, y: 300 },
        data: { label: "Denial Agent", description: "Handles rejections/appeals" }
      },
      {
        id: "output-1",
        type: "output",
        position: { x: 1100, y: 200 },
        data: { label: "Payment Posted", description: "ERA processed" }
      }
    ],
    edges: [
      { id: "e1", source: "trigger-1", target: "agent-1" },
      { id: "e2", source: "agent-1", target: "tool-1" },
      { id: "e3", source: "tool-1", target: "condition-1" },
      { id: "e4", source: "condition-1", target: "agent-2", label: "Yes" },
      { id: "e5", source: "condition-1", target: "agent-3", label: "No" },
      { id: "e6", source: "agent-2", target: "output-1" },
      { id: "e7", source: "agent-3", target: "agent-2" }
    ],
    status: "deployed",
    createdAt: "2026-02-01",
    updatedAt: "2026-02-20"
  }
]

export const categories = [
  "All Categories",
  "AI Agents",
  "MCP Servers",
  "MCP Tools",
  "Models",
  "Workflow Templates",
  "Claims Processing",
  "Denial Management",
  "Patient Collections",
  "Eligibility & Auth",
  "Coding & Charge Capture",
  "Payment Posting"
] as const
