// Package followup provides persistent follow-up reminders for Gas Town agents.
//
// When an agent defers work ("I'll wait for feedback"), they schedule a followup
// via `gt followup`. The followup is stored as a JSON file under the town's
// .runtime directory, surviving session restarts. The deacon patrol picks up
// overdue followups and re-engages the agent or escalates.
//
// Storage: <townRoot>/.runtime/followups/<agent-identity>/<id>.json
package followup

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/steveyegge/gastown/internal/constants"
)

// validIDPattern matches IDs generated by generateID (hex only).
var validIDPattern = regexp.MustCompile(`^[0-9a-f]+$`)

// Status represents the state of a followup reminder.
type Status string

const (
	StatusPending  Status = "pending"
	StatusOverdue  Status = "overdue"
	StatusResolved Status = "resolved"
)

// Followup represents a scheduled follow-up reminder.
type Followup struct {
	ID        string    `json:"id"`
	Agent     string    `json:"agent"`               // e.g. "gastown/polecats/Toast"
	Topic     string    `json:"topic"`                // what are we following up on
	BeadID    string    `json:"bead_id,omitempty"`    // optional linked bead
	DueAt     time.Time `json:"due_at"`               // when the followup fires
	CreatedAt time.Time `json:"created_at"`           // when it was scheduled
	Status    Status    `json:"status"`               // pending, overdue, resolved
	ResolvedAt *time.Time `json:"resolved_at,omitempty"` // when resolved
}

// followupsDir returns the directory for a given agent's followups.
func followupsDir(townRoot, agent string) string {
	safe := strings.ReplaceAll(agent, "/", "_")
	return filepath.Join(townRoot, constants.DirRuntime, "followups", safe)
}

// generateID returns a random hex ID for a followup.
func generateID() string {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		// Extremely unlikely; fall back to timestamp-based ID.
		return fmt.Sprintf("%x", time.Now().UnixNano())
	}
	return hex.EncodeToString(b[:])
}

// validateID checks that an ID is safe for use as a filename component.
func validateID(id string) error {
	if id == "" {
		return fmt.Errorf("empty followup ID")
	}
	if !validIDPattern.MatchString(id) {
		return fmt.Errorf("invalid followup ID %q: must be hex characters only", id)
	}
	return nil
}

// Create stores a new followup reminder and returns its ID.
func Create(townRoot, agent, topic string, dueAt time.Time, beadID string) (*Followup, error) {
	dir := followupsDir(townRoot, agent)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return nil, fmt.Errorf("creating followup dir: %w", err)
	}

	f := &Followup{
		ID:        generateID(),
		Agent:     agent,
		Topic:     topic,
		BeadID:    beadID,
		DueAt:     dueAt,
		CreatedAt: time.Now(),
		Status:    StatusPending,
	}

	data, err := json.MarshalIndent(f, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshaling followup: %w", err)
	}

	path := filepath.Join(dir, f.ID+".json")
	if err := os.WriteFile(path, data, 0644); err != nil {
		return nil, fmt.Errorf("writing followup: %w", err)
	}

	return f, nil
}

// List returns all followups for a given agent, sorted by due time.
func List(townRoot, agent string) ([]*Followup, error) {
	dir := followupsDir(townRoot, agent)
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading followups dir: %w", err)
	}

	var followups []*Followup
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			continue
		}
		var f Followup
		if err := json.Unmarshal(data, &f); err != nil {
			continue
		}
		followups = append(followups, &f)
	}

	sort.Slice(followups, func(i, j int) bool {
		return followups[i].DueAt.Before(followups[j].DueAt)
	})
	return followups, nil
}

// ListPending returns only pending (unresolved) followups for an agent.
func ListPending(townRoot, agent string) ([]*Followup, error) {
	all, err := List(townRoot, agent)
	if err != nil {
		return nil, err
	}
	var pending []*Followup
	for _, f := range all {
		if f.Status == StatusPending || f.Status == StatusOverdue {
			pending = append(pending, f)
		}
	}
	return pending, nil
}

// ListAllPending returns all pending followups across all agents.
// Used by deacon patrol to find overdue followups.
func ListAllPending(townRoot string) ([]*Followup, error) {
	baseDir := filepath.Join(townRoot, constants.DirRuntime, "followups")
	agentDirs, err := os.ReadDir(baseDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading followups base dir: %w", err)
	}

	var all []*Followup
	for _, agentDir := range agentDirs {
		if !agentDir.IsDir() {
			continue
		}
		// Read JSON files directly from this agent's directory.
		// Agent identity comes from the JSON content (f.Agent), not the dir name,
		// to avoid lossy round-trip of slash/underscore encoding.
		dirPath := filepath.Join(baseDir, agentDir.Name())
		files, err := os.ReadDir(dirPath)
		if err != nil {
			continue
		}
		for _, file := range files {
			if file.IsDir() || !strings.HasSuffix(file.Name(), ".json") {
				continue
			}
			data, err := os.ReadFile(filepath.Join(dirPath, file.Name()))
			if err != nil {
				continue
			}
			var f Followup
			if err := json.Unmarshal(data, &f); err != nil {
				continue
			}
			if f.Status == StatusPending || f.Status == StatusOverdue {
				all = append(all, &f)
			}
		}
	}

	sort.Slice(all, func(i, j int) bool {
		return all[i].DueAt.Before(all[j].DueAt)
	})
	return all, nil
}

// Resolve marks a followup as resolved.
func Resolve(townRoot, agent, id string) error {
	if err := validateID(id); err != nil {
		return err
	}

	dir := followupsDir(townRoot, agent)
	path := filepath.Join(dir, id+".json")

	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading followup %s: %w", id, err)
	}

	var f Followup
	if err := json.Unmarshal(data, &f); err != nil {
		return fmt.Errorf("parsing followup %s: %w", id, err)
	}

	now := time.Now()
	f.Status = StatusResolved
	f.ResolvedAt = &now

	updated, err := json.MarshalIndent(&f, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling followup: %w", err)
	}

	return os.WriteFile(path, updated, 0644)
}

// IsOverdue returns true if the followup's due time has passed.
func (f *Followup) IsOverdue() bool {
	return f.Status == StatusPending && time.Now().After(f.DueAt)
}

// TimeUntilDue returns the duration until the followup is due.
// Negative means overdue.
func (f *Followup) TimeUntilDue() time.Duration {
	return time.Until(f.DueAt)
}
