package doltserver

import (
	"bytes"
	"fmt"
	"os/exec"
	"strconv"
	"strings"
)

// generateCrossRigViews discovers all databases with beads tables and generates
// CREATE OR REPLACE VIEW statements for cross-rig views. This replaces the old
// static init SQL that hardcoded rig names.
func generateCrossRigViews(port int) (string, error) {
	// Discover databases that have an 'issues' table with actual data.
	// We filter to non-empty databases to avoid expensive 18-way UNIONs
	// over empty test databases that slow down Grafana queries.
	rigs, err := discoverNonEmptyRigDatabases(port, "issues")
	if err != nil {
		return "", fmt.Errorf("discover rig databases: %w", err)
	}
	if len(rigs) == 0 {
		return "-- No rig databases found with issues table\n", nil
	}

	var buf strings.Builder
	buf.WriteString("-- Auto-generated cross-rig views (do not edit)\n")
	buf.WriteString("-- Generated by doltserver.generateCrossRigViews()\n\n")

	// v_all_issues
	buf.WriteString("CREATE OR REPLACE VIEW v_all_issues AS\n")
	for i, rig := range rigs {
		if i > 0 {
			buf.WriteString("UNION ALL\n")
		}
		fmt.Fprintf(&buf, "SELECT '%s' AS rig, id, title, status, priority, issue_type, assignee, created_at, closed_at FROM `%s`.issues\n", rig, rig)
	}
	buf.WriteString(";\n\n")

	// v_all_wisps — only include databases that have a wisps table
	wispRigs, _ := discoverRigDatabases(port, "wisps")
	if len(wispRigs) > 0 {
		buf.WriteString("CREATE OR REPLACE VIEW v_all_wisps AS\n")
		for i, rig := range wispRigs {
			if i > 0 {
				buf.WriteString("UNION ALL\n")
			}
			fmt.Fprintf(&buf, "SELECT '%s' AS rig, id, title, status, created_at FROM `%s`.wisps\n", rig, rig)
		}
		buf.WriteString(";\n\n")
	}

	// v_all_labels — only include databases that have a labels table
	labelRigs, _ := discoverRigDatabases(port, "labels")
	if len(labelRigs) > 0 {
		buf.WriteString("CREATE OR REPLACE VIEW v_all_labels AS\n")
		for i, rig := range labelRigs {
			if i > 0 {
				buf.WriteString("UNION ALL\n")
			}
			fmt.Fprintf(&buf, "SELECT '%s' AS rig, issue_id, label FROM `%s`.labels\n", rig, rig)
		}
		buf.WriteString(";\n\n")
	}

	return buf.String(), nil
}

// discoverRigDatabases queries information_schema for databases containing the given table.
// Returns database names sorted alphabetically.
func discoverRigDatabases(port int, tableName string) ([]string, error) {
	query := fmt.Sprintf(
		"SELECT DISTINCT TABLE_SCHEMA FROM information_schema.TABLES WHERE TABLE_NAME = '%s' ORDER BY TABLE_SCHEMA",
		tableName,
	)

	cmd := exec.Command("mysql", "-h", "127.0.0.1", "-P", strconv.Itoa(port),
		"-u", "root", "-N", "-B", "-e", query)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("%v: %s", err, stderr.String())
	}

	var rigs []string
	for _, line := range strings.Split(strings.TrimSpace(stdout.String()), "\n") {
		line = strings.TrimSpace(line)
		if line != "" && line != "information_schema" {
			rigs = append(rigs, line)
		}
	}
	return rigs, nil
}

// discoverNonEmptyRigDatabases returns databases that have the given table AND at least one row.
func discoverNonEmptyRigDatabases(port int, tableName string) ([]string, error) {
	allRigs, err := discoverRigDatabases(port, tableName)
	if err != nil {
		return nil, err
	}

	var nonEmpty []string
	for _, rig := range allRigs {
		query := fmt.Sprintf("SELECT EXISTS(SELECT 1 FROM `%s`.`%s` LIMIT 1)", rig, tableName)
		cmd := exec.Command("mysql", "-h", "127.0.0.1", "-P", strconv.Itoa(port),
			"-u", "root", "-N", "-B", "-e", query)
		var stdout bytes.Buffer
		cmd.Stdout = &stdout
		if err := cmd.Run(); err != nil {
			continue // skip databases we can't query
		}
		if strings.TrimSpace(stdout.String()) == "1" {
			nonEmpty = append(nonEmpty, rig)
		}
	}
	return nonEmpty, nil
}
